# The QR Algorithm

We conduct two numerical experiments to illustrate the convergence rate study in the theory. To that end, we construct a random 4 × 4 matrix with eigenvalues 1, 2, 3, and 4.


In [63]:
import numpy as np
import matplotlib.pyplot as plt

# Crear una matriz de ejemplo
D = np.diag([4, 3, 2, 1])
np.random.seed(0)
S = np.random.rand(4, 4) * 2 - 1
A = S @ D @ np.linalg.inv(S) #np.dot(S, np.dot(D, np.linalg.inv(S)))

# Imprimir la matriz original A
print("Matriz original A")
print(A)


Matriz original A
[[ 2.60165071  0.04030111  0.12143969  0.22085621]
 [ 1.0856164   0.91638494 -0.6213239  -0.00480855]
 [-1.82537694  0.95116009  4.21246033  0.92894433]
 [ 0.8191164   1.21687947  0.36809039  2.26950402]]


Comprobamos que la matriz A y la matriz D tienen efectivamente los mismos autovalores:

In [64]:
eigenvaluesA, eigenvectorsA = np.linalg.eig(A)
eigenvaluesD, eigenvectorsD = np.linalg.eig(D)
print("Matriz A")
print(eigenvaluesA)
print("Matriz D")
print(eigenvaluesD)

Matriz A
[1. 2. 3. 4.]
Matriz D
[4. 3. 2. 1.]


En el siguiente paso, vemos como realizar la descomposición QR de la matriz A

In [65]:
Q,R = np.linalg.qr(A)

print("Matriz A")
print(A)
print("Matriz Q")
print(Q)
print("Matriz R")
print(R)
print("Matriz producto QR")
print(Q @ R)


Matriz A
[[ 2.60165071  0.04030111  0.12143969  0.22085621]
 [ 1.0856164   0.91638494 -0.6213239  -0.00480855]
 [-1.82537694  0.95116009  4.21246033  0.92894433]
 [ 0.8191164   1.21687947  0.36809039  2.26950402]]
Matriz Q
[[-0.75259821  0.02125927 -0.65761852 -0.02611229]
 [-0.31404406 -0.49274815  0.37210841 -0.72118716]
 [ 0.52803992 -0.56107146 -0.61591565 -0.16437935]
 [-0.23695169 -0.66479029  0.22298231  0.67244826]]
Matriz R
[[-3.45689196 -0.10420695  2.24085535 -0.21194902]
 [ 0.         -1.79332864 -2.29945626 -2.02288373]
 [ 0.          0.         -2.82350346 -0.21312054]
 [ 0.          0.          0.          1.37112556]]
Matriz producto QR
[[ 2.60165071  0.04030111  0.12143969  0.22085621]
 [ 1.0856164   0.91638494 -0.6213239  -0.00480855]
 [-1.82537694  0.95116009  4.21246033  0.92894433]
 [ 0.8191164   1.21687947  0.36809039  2.26950402]]


Ahora toca definir el algoritmo QR para el calculo de autovalores

In [66]:

def basic_qr_algorithm(A, max_iterations=20):
    """
    Implementación del algoritmo QR básico para la descomposición de Schur.
    
    Args:
    A (numpy.ndarray): Matriz cuadrada de entrada.
    max_iterations (int): Número máximo de iteraciones del algoritmo QR.
    
    Returns:
    T (numpy.ndarray): Matriz triangular superior (parte triangular de la descomposición de Schur).
    U (numpy.ndarray): Matriz ortogonal (parte ortogonal de la descomposición de Schur).
    """
    n = A.shape[0]
    Uk = np.eye(n)
    Ak = A.copy()

    for _ in range(max_iterations):
        Qk, Rk = np.linalg.qr(Ak)
        Ak = Rk @ Qk #np.dot(Rk, Qk)
        Uk = Uk @ Qk #np.dot(Uk, Qk)

    return Ak, Uk


Por último, aplicamos el algoritmo 

In [67]:
# Aplicar el algoritmo QR básico
T, U = basic_qr_algorithm(A)

# Imprimir la matriz triangular superior obtenida
print("Matriz triangular superior T después de iteraciones:")
print(T)

# Imprimir la matriz Q
print("Matriz triangular superior U después de iteraciones:")
print(U)

Matriz triangular superior T después de iteraciones:
[[ 3.99919990e+00 -1.12805885e-01  1.54041354e+00  2.16273273e+00]
 [-7.09936420e-03  3.00087477e+00  1.27345338e+00 -4.88225607e-02]
 [-2.48643314e-06 -5.67772208e-05  1.99992651e+00  9.13672037e-01]
 [ 9.10644610e-13  3.68428516e-10 -1.29531075e-06  9.99998816e-01]]
Matriz triangular superior U después de iteraciones:
[[-0.09918471  0.43408535  0.82422166  0.34984419]
 [ 0.16186078  0.26839913  0.26515728 -0.91184133]
 [-0.97228006 -0.11917527  0.03018344 -0.19889117]
 [-0.13650994  0.85166253 -0.49943892  0.08122029]]


Comprobamos que efectivamente esto nos da la descomposición de Schur

In [68]:
U @ T @ U.conj().T
print(U @ T @ U.transpose()-A)

[[ 5.77315973e-15  1.22124533e-15 -2.31759056e-15  3.05311332e-15]
 [ 2.66453526e-15 -2.22044605e-16 -1.22124533e-15  1.35655376e-15]
 [-2.88657986e-15  2.66453526e-15  8.88178420e-16 -1.77635684e-15]
 [ 7.43849426e-15  3.55271368e-15 -1.72084569e-15  4.44089210e-15]]


## EJERCICIO 1:

Dividir elemento a elemento A(20)/A(19) y observar la tasa de convergencia de cada uno de los elementos. Comprobar que se verifica lo estudiado en la teoría.

In [69]:
T20, U20 = basic_qr_algorithm(A,20)
T19, U19 = basic_qr_algorithm(A,19)
print(T20/T19)

[[ 1.00007181  0.9798758   0.99804907 -1.00005656]
 [ 0.75059909  0.99989163  1.00289455 -0.90557322]
 [ 0.5001163   0.66762515  1.00001844 -1.00000284]
 [-0.25006698 -0.33326437 -0.50010833  1.00000118]]


## EJERCICIO 2:

Utilizar ahora el mismo script pero con la matriz D = np.diag([5, 2, 2, 1]) y dividir elemento a elemento A(20)/A(19). Observar la tasa de convergencia de cada uno de los elementos. Comprobar que se verifica lo estudiado en la teoría.

In [70]:
T20, U20 = basic_qr_algorithm(A,20)
T19, U19 = basic_qr_algorithm(A,19)
print(T20/T19)

[[ 1.00007181  0.9798758   0.99804907 -1.00005656]
 [ 0.75059909  0.99989163  1.00289455 -0.90557322]
 [ 0.5001163   0.66762515  1.00001844 -1.00000284]
 [-0.25006698 -0.33326437 -0.50010833  1.00000118]]
