# Descomposición SVD (Singular Value Decomposition)

# Introduction

La descomposición en valores singulares de una matriz tiene muchas aplicaciones. Aquí veremos la base en python y luego en otro notebook veremos cómo se puede utilizar la descomposición en valores singulares en la compresión de imágenes.

Cualquier matriz $A$ puede descomponerse en tres matrices $U$, $\Sigma$ y $V$ de modo que $A = U \Sigma V$, esto se llama descomposición en valores singulares. Las columnas de $U$ y $V$ son ortonormales y $\Sigma$ es diagonal. La mayoría de los paquetes de computación científica tienen una función para calcular la descomposición en valores singulares, no entraré en detalles sobre cómo encontrar $U$, $\Sigma$ y $V$ aquí. En la teoría, escribimos la descomposición como $A = U \Sigma V^T$, de modo que su $V^T$ es nuestro $V$. El uso en este cuaderno es coherente con cómo la función de descomposición en valores singulares de numpy devuelve $V$.

## Ejemplo con una matriz pequeña $A$:

If $A = \begin{bmatrix} 1 & 0 \\ 1 & 2 \end{bmatrix}$
                     
$A$ puede ser escrita como $U \Sigma V$, donde $U$, $\Sigma$ y $V$ son, redondeadas a 2 lugares decimales:

$U = \begin{bmatrix} -0.23 & -0.97 \\ -0.97 & 0.23 \end{bmatrix}$
                     
$S = \begin{bmatrix} 2.29 & 0 \\ 0 & 0.87 \end{bmatrix}$
                     
$V = \begin{bmatrix} -0.53 & -0.85 \\ -0.85 & 0.53 \end{bmatrix}$

Veamos como hacer esto con python. Primero creamos nuestra matriz

In [22]:
import numpy as np

# Create a 2x2 matrix
A = np.matrix([[1, 0], [1, 2]])

# Print the matrix
print(A)


[[1 0]
 [1 2]]


En siguiente lugar, descomponemos A=USV usando la función de python

In [23]:
U, sigma, V = np.linalg.svd(A)
print(U)
print(sigma)
print(V)

[[-0.22975292 -0.97324899]
 [-0.97324899  0.22975292]]
[2.28824561 0.87403205]
[[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]


# Ejercicio 1: 
Comprobar que los términos de la diagonal de S son los autovalores de $A^TA$ y que las columnas de $V$ están formadas por autovectores de $A^TA$. Comprobar también que las columnas de $U$ están formadas por autovectores de $AA^T$

In [24]:
ATA=np.matrix(A.T * A) 
print(ATA)

[[2 2]
 [2 4]]


In [25]:
eigenvalues, eigenvectors = np.linalg.eig(ATA)
print(eigenvalues)
print(eigenvalues**0.5)
print(eigenvectors)

[0.76393202 5.23606798]
[0.87403205 2.28824561]
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [26]:
AAT=np.matrix(A * A.T) 
print(AAT)

[[1 1]
 [1 5]]


In [27]:
eigenvalues, eigenvectors = np.linalg.eig(AAT)
print(eigenvalues)
print(eigenvalues**0.5)
print(eigenvectors)

[0.76393202 5.23606798]
[0.87403205 2.28824561]
[[-0.97324899 -0.22975292]
 [ 0.22975292 -0.97324899]]


# Aplicación de la descomposición SVD

Podemos reconstruir la matriz completa utilizando la descomposición SVD

In [28]:
n_of_modes = 2 #Number of modes to be used in the reconstruction

matrix_approx = np.matrix(U[:, :n_of_modes]) * np.diag(sigma[:n_of_modes]) * np.matrix(V[:n_of_modes, :])
print(matrix_approx)

[[ 1.00000000e+00 -3.88578059e-16]
 [ 1.00000000e+00  2.00000000e+00]]


Si no utilizamos todos los modos, tenemos una representación aproximada de la matriz, lo que permite comprimir la información. El tamaño de los valores singulares nos da una idea de su importancia a la hora de recomponer la matriz

In [29]:
n_of_modes = 1 #Number of modes to be used in the reconstruction

matrix_approx = np.matrix(U[:, :n_of_modes]) * np.diag(sigma[:n_of_modes]) * np.matrix(V[:n_of_modes, :])
print(matrix_approx)

[[0.2763932  0.4472136 ]
 [1.17082039 1.89442719]]


En esta idea se basa la aplicación de compresión de imágenes, que veremos en la siguiente sección.
Otras aplicaciones de la descomposición SVD incluyen Machine Learning (https://jonathan-hui.medium.com/machine-learning-singular-value-decomposition-svd-principal-component-analysis-pca-1d45e885e491) o mecánica de fluidos computacional (https://en.wikipedia.org/wiki/Proper_orthogonal_decomposition). 